"""v2 baseline schema

Revision ID: 8d4ec3b4729d
Revises: 
Create Date: 2026-07-19 02:48:47.255300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4ec3b4729d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_key'), 'badges', ['key'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_key'), 'categories', ['key'], unique=True)
    op.create_table('descriptors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descriptors_label'), 'descriptors', ['label'], unique=True)
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sub', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('logic', sa.Text(), nullable=True),
    sa.Column('evolution', sa.Text(), nullable=True),
    sa.Column('tip', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_key'), 'families', ['key'], unique=True)
    op.create_table('flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavors_label'), 'flavors', ['label'], unique=True)
    op.create_table('glasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glasses_key'), 'glasses', ['key'], unique=True)
    op.create_table('kitchen_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_categories_slug'), 'kitchen_categories', ['slug'], unique=True)
    op.create_table('spirit_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spirit_categories_slug'), 'spirit_categories', ['slug'], unique=True)
    op.create_table('spirits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spirits_key'), 'spirits', ['key'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_key'), 'tags', ['key'], unique=True)
    op.create_table('timeline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('classics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('glass_id', sa.Integer(), nullable=True),
    sa.Column('garnish', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('for_whom', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['glass_id'], ['glasses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classics_family_id'), 'classics', ['family_id'], unique=False)
    op.create_index(op.f('ix_classics_slug'), 'classics', ['slug'], unique=True)
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('is_alcoholic', sa.Boolean(), nullable=False),
    sa.Column('is_zero_culture', sa.Boolean(), nullable=False),
    sa.Column('abv', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('abv_raw', sa.String(length=32), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('price_raw', sa.String(length=64), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('caffeine_level', sa.Integer(), nullable=True),
    sa.Column('is_carbonated', sa.Boolean(), nullable=True),
    sa.Column('glass_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.Text(), nullable=True),
    sa.Column('garnish', sa.Text(), nullable=True),
    sa.Column('pitch', sa.Text(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('naming', sa.Text(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['glass_id'], ['glasses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinks_slug'), 'drinks', ['slug'], unique=True)
    op.create_table('kitchen_dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('price_raw', sa.String(length=32), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timing_min_low', sa.Integer(), nullable=True),
    sa.Column('timing_min_high', sa.Integer(), nullable=True),
    sa.Column('timing_raw', sa.String(length=32), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('weight_raw', sa.String(length=64), nullable=True),
    sa.Column('kcal_portion', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carb_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('kcal_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('nutrition_raw', sa.Text(), nullable=True),
    sa.Column('serving', sa.Text(), nullable=True),
    sa.Column('interesting_facts', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['kitchen_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_dishes_category_id'), 'kitchen_dishes', ['category_id'], unique=False)
    op.create_index(op.f('ix_kitchen_dishes_slug'), 'kitchen_dishes', ['slug'], unique=True)
    op.create_table('learning_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'kind', 'slug')
    )
    op.create_table('spirit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('abv', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('abv_raw', sa.String(length=32), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('serving_ml', sa.Integer(), nullable=True),
    sa.Column('price_raw', sa.String(length=64), nullable=True),
    sa.Column('flavour', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('cocktail_pairings', sa.Text(), nullable=True),
    sa.Column('fact', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['spirit_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spirit_entries_category_id'), 'spirit_entries', ['category_id'], unique=False)
    op.create_index(op.f('ix_spirit_entries_slug'), 'spirit_entries', ['slug'], unique=True)
    op.create_table('classic_descriptors',
    sa.Column('classic_id', sa.Integer(), nullable=False),
    sa.Column('descriptor_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classic_id'], ['classics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descriptor_id'], ['descriptors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classic_id', 'descriptor_id')
    )
    op.create_table('classic_related_drinks',
    sa.Column('classic_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classic_id'], ['classics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classic_id', 'drink_id')
    )
    op.create_table('classic_spirits',
    sa.Column('classic_id', sa.Integer(), nullable=False),
    sa.Column('spirit_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classic_id'], ['classics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spirit_id'], ['spirits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classic_id', 'spirit_id')
    )
    op.create_table('drink_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_details_drink_id'), 'drink_details', ['drink_id'], unique=False)
    op.create_table('drink_flavors',
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('flavor_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drink_id', 'flavor_id')
    )
    op.create_table('drink_spirits',
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('spirit_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spirit_id'], ['spirits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drink_id', 'spirit_id')
    )
    op.create_table('drink_tags',
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drink_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink_tags')
    op.drop_table('drink_spirits')
    op.drop_table('drink_flavors')
    op.drop_index(op.f('ix_drink_details_drink_id'), table_name='drink_details')
    op.drop_table('drink_details')
    op.drop_table('classic_spirits')
    op.drop_table('classic_related_drinks')
    op.drop_table('classic_descriptors')
    op.drop_index(op.f('ix_spirit_entries_slug'), table_name='spirit_entries')
    op.drop_index(op.f('ix_spirit_entries_category_id'), table_name='spirit_entries')
    op.drop_table('spirit_entries')
    op.drop_table('learning_progress')
    op.drop_index(op.f('ix_kitchen_dishes_slug'), table_name='kitchen_dishes')
    op.drop_index(op.f('ix_kitchen_dishes_category_id'), table_name='kitchen_dishes')
    op.drop_table('kitchen_dishes')
    op.drop_index(op.f('ix_drinks_slug'), table_name='drinks')
    op.drop_table('drinks')
    op.drop_index(op.f('ix_classics_slug'), table_name='classics')
    op.drop_index(op.f('ix_classics_family_id'), table_name='classics')
    op.drop_table('classics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('timeline_entries')
    op.drop_index(op.f('ix_tags_key'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_spirits_key'), table_name='spirits')
    op.drop_table('spirits')
    op.drop_index(op.f('ix_spirit_categories_slug'), table_name='spirit_categories')
    op.drop_table('spirit_categories')
    op.drop_index(op.f('ix_kitchen_categories_slug'), table_name='kitchen_categories')
    op.drop_table('kitchen_categories')
    op.drop_index(op.f('ix_glasses_key'), table_name='glasses')
    op.drop_table('glasses')
    op.drop_index(op.f('ix_flavors_label'), table_name='flavors')
    op.drop_table('flavors')
    op.drop_index(op.f('ix_families_key'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_descriptors_label'), table_name='descriptors')
    op.drop_table('descriptors')
    op.drop_index(op.f('ix_categories_key'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_badges_key'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
